### ISSUE TITLE
Add ImgBot to the project

### ISSUE THREAD

**Issue by Aisuko** [layer5io/layer5#1494]
**Current Behavior**

This project includes many static resources especially JPG and PNG.

**Desired Behavior**

We should resize the static resources to a small size if it can be. So, we can import ImgBot into our project as a static resource manager. Actually, we did this already in our other projects like `meshery` and `meshry.io` if I remember right.

---
[Optional] **Screenshots / Mockups**

[Optional] **Alternatives**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by Aisuko** [comment]
There is no standard rule of the static resources for the project, we just want the repo easy to clone and to contribute.

**Comment by leecalcote** [comment]
Good suggestion, @Aisuko. Imgbot is enabled across all repos under the `layer5io` org. [Imgbot's activities in this `layer5` repo](https://github.com/layer5io/layer5/pulls?page=1&q=is%3Apr+author%3Aapp%2Fimgbot) were last seen this past December. I assume that's because almost all energy has been redirected into the `layer5-ng` branch and so there hasn't been a need to fire on `master` in that time period (master being the currently published branch).

**Comment by Aisuko** [comment]
Close due to the comment above.
