### ISSUE TITLE
[Community] Member Profile:

### ISSUE THREAD

**Issue by sayantan1413** [layer5io/layer5#2035]
**Current Behavior**

@debjani1413  has been a consistent contributor and community member.🚀

**Desired Situation**
Let's recognize @debjani1413  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: debjani1413
- Twitter: 
- LinkedIn: debjani-dey-4981281ab
- Link to profile picture: https://drive.google.com/file/d/14Te2VWdeV84ywXPGvBsFTHC4pcjpf8qL/view?usp=drivesdk

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

The CONTRIBUTING.md file has a "Common Types of Site Updates" section with detailed examples to follow here.[CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by sayantan1413** [comment]
Hey @debjani1413 can you please share your bio and your location here ?

**Comment by debjani1413** [comment]
Bio:  I am Debjani Dey, currently one year behind in graduating as a Computer Science Engineer. I got into this project some two months back and since then have been contributing to the project, mainly to the documentation domain. My interests lies on, websites, writing and nonetheless sleeping 😴. I'm immensely pleasured by the opportunities that I got while contributing here, and I really hope there is more to come!

Localtion: Kolkata
