### ISSUE TITLE
Add Patterns Badge to the Members page filter

### ISSUE THREAD

**Issue by debo19** [layer5io/layer5#2479]
**Current Behavior**
The filter on https://layer5.io/community/members does not contain the Patterns badge.

![Members _ Layer5 - The Service Mesh Company - Google Chrome 15-01-2022 03_40_09 (2)](https://user-images.githubusercontent.com/85789734/149592062-eb8d02b5-dbac-4848-aaf5-e077556080d0.png)

**Desired Situation**

Add the Service Mesh Patterns Badge as an option under the Badges category.

---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by verma-kunal** [comment]
Hey @debo19 , I would like to work on this 🙂

**Comment by warunicorn19** [comment]
Go ahead @verma-kunal

**Comment by verma-kunal** [comment]
Going through the file system that is being followed in the file [here](https://github.com/layer5io/layer5/blob/master/src/pages/community/members.js) i think we would need to create a folder named as `Patterns` & then the .svg image (logo) inside that, so that we can import & use it in the `js` file

Is this what the right approach would look like? Actually I just have a basic knowledge of Js, so by understanding the file system through the code, came up onto this conclusion

**Comment by verma-kunal** [comment]
Sure, thanks! 👍

**Comment by verma-kunal** [comment]
Sorry for the delay! Was stuck in a part & had to figure that out!
Thanks to @debo19 & @warunicorn19 for guiding 🙂
