### ISSUE TITLE
[Community] Member Profile: Aman Shrivastava

### ISSUE THREAD

**Issue by aman34503** [layer5io/layer5#2532]
**Current Behavior**

<@aman34503> has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @aman34503 as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: aman34503
- Twitter: amanscasm
- LinkedIn: /aman-shrivastava04/
- Link to profile picture: https://drive.google.com/file/d/1-WVplvlNFVDm5nSh5sk__LAByerYdE1-/view?usp=sharing

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by warunicorn19** [comment]
This is great. We would love for you to have a member profile. Individuals that have profiles are those that have been recognized for their contribution to our projects and have demonstrated their cultural fit with community values. We so very much hope that this is you, too, someday. Since this isn’t the case currently, we'll be closing this issue for now. Why don't you get started with some `good first issues`: https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Ameshery+org%3Alayer5io+org%3Aservice-mesh-performance+label%3A%22help+wanted%22+
