### ISSUE TITLE
[Meshery] Integrations: Background shadow being cutoff

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3359]
#### Description
The shadow behind the individual cells inside of the Integrations honeycomb is being cutoff. See the screenshot below:

<img width="1063" alt="Screen Shot 2022-10-17 at 1 14 43 PM" src="https://user-images.githubusercontent.com/7570704/196252465-12c357a4-eb0b-472d-bfad-c410b0af7fe6.png">

Example page - https://layer5.io/cloud-native-management/meshery/integrations/cubefs
Source code - https://github.com/layer5io/layer5/tree/master/src/sections/Meshery/Meshery-integrations

#### Expected Behavior
The shadow should be allowed to overflow and remain visible.

#### Environment:
- Host OS: macOS
- Browser: Safari

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by sayan404** [comment]
I want to work in this issue please assign me this issue @leecalcote

**Comment by leecalcote** [comment]
Thanks, @sayan404. 👍

**Comment by sayan404** [comment]
Unfortunately I cannot do this work now ... please assign this issue to someone else @leecalcote

**Comment by eeshaanSA** [comment]
updates? @AbhishekTiwari23

**Comment by AbhishekTiwari23** [comment]
> updates? @AbhishekTiwari23

Hello @eeshaanSA, I mentioned on slack that I will be unavailable till Dec 15 because of my end-semester exams. I will be regular after 15. 
Thanks.

**Comment by leecalcote** [comment]
Sounds good, @gopivaibhav

**Comment by gopivaibhav** [comment]
Hi @leecalcote Since this issue was a bit old, this was an issue long back. I don't think there is some problem now as there are some commits made in this file to change tags to filter, styling cards, etc,. I checked it in my browser now and I can't see that shadow cutoff  (I use Linux and Brave browser)
![image](https://user-images.githubusercontent.com/78922463/206979168-90c2a736-d64f-4f45-a136-56fe85b21c7c.png)

And I didn't check in the given environment i.e. 
- Host OS: macOS
- Browser: Safari

If I want to check in the mentioned environment, then Can you please let me know how am I supposed to check?

**Comment by UtkarshMishra12** [comment]
@leecalcote ^^

**Comment by leecalcote** [comment]
yes, I can confirm that this issue still remains.

**Comment by randychilau** [comment]
Hi @leecalcote, @gopivaibhav 

I am new to contributing, and thought I could assist @gopivaibhav on this open issue since I have the environment:
- Host OS: macOS
- Browser: Safari

In Safari, I was experiencing flicker/cutoff when hovering over the hexagons. [Others reported](https://www.google.com/search?q=translatez+safari+flicker) related Safari issues and suggested adding `-webkit-transform: translateZ(0)` ([MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/translateZ)). 

I gave it a try in the following file "layer5/src/sections/Meshery/Meshery-integrations/Integration.style.js" 
```
.container-active,
  .container-inactive {
    -webkit-transform: translateZ(0);
```
and it seems to resolve the flicker/cutoff in Safari ([flicker gif](https://gifyu.com/image/S7cgk) / [with translateZ gif](https://gifyu.com/image/S7cg9))

Hope this helps @gopivaibhav, cheers!

**Comment by leecalcote** [comment]
This is most helpful, @randychilau. I encourage you to push forward with a PR, if you would like.

Also, here is another issue to be aware of - https://github.com/layer5io/layer5/issues/3809. // @divz-codess

**Comment by randychilau** [comment]
Happy to be able to contribute, I will do a PR. Thanks!
