### ISSUE TITLE
[White Logo] Need a new white logo for kubewarden

### ISSUE THREAD

**Issue by kamalbuilds** [layer5io/layer5#3430]
**Current Behavior**

Actual color logo -
![image](https://user-images.githubusercontent.com/95926324/199081907-ec016f93-8063-46e1-812a-1998b375dabc.png)

Current white logo - https://landscape.cncf.io/logos/kubewarden.svg
**Desired Situation**

The white logo needs enhancements
---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by aditi5050** [comment]
@legendarykamal I would like to work on this can you please assign this to me.

**Comment by sahilsuman933** [comment]
Go ahead, @aditi5050!

**Comment by rakshitgondwal** [comment]
Hey @aditi5050! How are you coming up with this issue? btw @legendarykamal, I didn't understand what changes we need in this logo. Do we need a black and white logo or what?

**Comment by legendarykamal** [comment]
yeah a white logo for `kubegarden` as with css it is unrecognisable and hence undesirable.

**Comment by rakshitgondwal** [comment]
> yeah a white logo for `kubegarden` as with css it is unrecognisable and hence undesirable.

Cool. If @aditi505 is unable to solve this, I would like to work on this or else I can also help her as I am proficient with photoshop.

**Comment by rakshitgondwal** [comment]
Should I work on this? @legendarykamal

**Comment by legendarykamal** [comment]
go on @rakshitgondwal  .

**Comment by rakshitgondwal** [comment]
In which directory am I supposed to upload the logo? @legendarykamal

**Comment by UtkarshMishra12** [comment]
@rakshitgondwal Please update!!

**Comment by rakshitgondwal** [comment]
> @rakshitgondwal Please update!!

So sorry for not updating was busy due to college exams. I was done with this issue a long time ago but I didn't knew how should I submit the logo? Can you guide me on this?

**Comment by leecalcote** [comment]
@rakshitgondwal it so happens that the data source for integration details is this spreadsheet - https://docs.google.com/spreadsheets/d/1DZHnzxYWOlJ69Oguz4LkRVTFM79kC2tuvdwizOJmeMw/edit#gid=0. You can add a comment on the respective cell with the SVG inside or paste here and then link to here.

**Comment by rakshitgondwal** [comment]
![kubewarden](https://user-images.githubusercontent.com/98955085/209177490-51c17577-ee50-4e1a-9b60-b8ed7076f294.png)

**Comment by rakshitgondwal** [comment]
@leecalcote Please check

**Comment by UtkarshMishra12** [comment]
@leecalcote ^^

**Comment by Sachinsharmak** [comment]
Is this issue still open?

**Comment by Darrendsouza1111** [comment]
can i work on this is it still open?

**Comment by HemanthPaila** [comment]
Hey, @legendarykamal can I work on it?

**Comment by legendarykamal** [comment]
I think yes its open  , but not sure . 
Sorry, I have been away .

@UtkarshMishra12 or Mr. @leecalcote could better confirm on this .

**Comment by leecalcote** [comment]
Tagging @Shivam-AfA to triage.

**Comment by Shivam-AfA** [comment]
@leecalcote Currently, We do not have the Kuberwarden integration listed in the spreadsheet. If we do support this integration, it should be added in the spreadsheet.

**Comment by shindodkar** [comment]
@Shivam-AfA   I would like to work on it

**Comment by randychilau** [comment]
Hi All,

Not sure if this may be blocked due to some confusion, but perhaps a general summary could allow this to move forward or be closed.

- The issue creator's request for a white Kubewarden SVG logo has been [fulfilled](https://github.com/layer5io/layer5/issues/3430#issuecomment-1363027193) by @rakshitgondwal
- However, as @Shivam-AfA has noted, there is no current need for the SVG since there is no active Kubewarden Meshery integration in the [spreadsheet](https://docs.google.com/spreadsheets/d/1DZHnzxYWOlJ69Oguz4LkRVTFM79kC2tuvdwizOJmeMw/edit#gid=345660040) workflow tab `Meshery Integrations` mentioned by @leecalcote.

- Potential options to close the issue
   - someone with write access can create and save an entry for Kubewarden in the `Meshery Integrations` tab for potential use in the future, but not publish it and keep it inactive.
   
      or

   - since @rakshitgondwal has already added a comment to the spreadsheet with a link to the SVG [as directed](https://github.com/layer5io/layer5/issues/3430#issuecomment-1362961383), the svg is available for potential future use and this issue can be closed.
   ![image](https://github.com/layer5io/layer5/assets/90356410/e3d01bc8-df2b-4a4d-a705-606d1a0863f4)

Hope that helps.

Cheers,
Randy
