### ISSUE TITLE
[Performance] Fix the `csp-xss` rule reported by lighthouse ci

### ISSUE THREAD

**Issue by ayushthe1** [layer5io/layer5#3695]
### Description

Currently the lighthouse ci tests are failing for [csp-xss](https://github.com/layer5io/layer5/actions/runs/4088178421/jobs/7049562479#step:6:40) test 

### Expected Behavior

This assertion test needs to be fixed and a strict content-security-policy needs to be enabled.

Some resources to help solve this issue: 
https://www.isaacsmith.us/blog/2022/add-csp-to-github-pages
https://web.dev/strict-csp/

### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by ayushthe1** [comment]
**Note that** the `csp-xss` test has been disabled for the time being by the PR #3694 until this issue gets solved

**Comment by RishabhKodes** [comment]
@ayushthe1 I can take up this issue.

**Comment by ayushthe1** [comment]
Thanks @RishabhKodes . Assigned you the issue.

**Comment by RishabhKodes** [comment]
@ayushthe1, the logs for the run you have mentioned have expired https://github.com/layer5io/layer5/actions/runs/4088178421/jobs/7049562479#step:6:40. Can you please share another log with this issue.

**Comment by ayushthe1** [comment]
here's another [reference](https://github.com/ayushthe1/layer5/actions/runs/3997381074/jobs/6858634261#step:6:58).

**Comment by RishabhKodes** [comment]
Hi @ayushthe1, after digging into this issue and a lot of other GitHub threads related to csp-xss, I have concluded some points.
1. Adding strict csp-xss rules will definitely affect the functionality of the website and many resources/pages might not work as they should because of the restrictions on resources that we are using. For eg - images, CSS, fonts, etc.
2. csp rules are too strict and we can never achieve it to be 100% safe (considering the varied resources we use on the website).
3. Some warnings that we see as high or severe in nature in the lighthouseci logs are not actually severe in nature and that has to be updated from their side.
4. If the CSPs are implemented somehow, we need to ensure we also have sufficient fallbacks in place for some old browsers that are incompatible.

**Solutions**
1. If there's still a need for a CSP, I can use the `gatsby-plugin-csp` for creating one. 
2. It's best that we keep the `csp-xss` test disabled and run the lighthouseci without that. The csp-xss metric is not even included in the Best Performance attribute in the Lighthouse, so it's fine to keep it disabled.

Some links for reference
[1] https://github.com/GoogleChrome/lighthouse/issues/12804
[2] https://tempered.works/posts/2018-08-19-setting-up-a-gatsby-site/ (see the csp score here)
[3] https://www.gatsbyjs.com/plugins/gatsby-plugin-csp/#options

**Comment by ayushthe1** [comment]
Thanks @RishabhKodes for doing the research. You do have a valid point in keeping the `csp-xss` test disabled. But i can't really decide what should be done.
I will tag @Nikhil-Ladha ,to further evaluate on this.

**Comment by Nikhil-Ladha** [comment]
That is some good research @RishabhKodes 👌🏼 .
I second that CSP is a bit of a stretch for static site generators and can be a PITA. Luckily, gatsby provides a plugin for the same but again that is not helpful for our case due to the usage of external scripts like google analytics, and to allow that we would have to disable the hashing directives which makes it the same as almost not having anything entirely.

However, let's go ahead and add that plugin to just have a thin layer of XSS protection (though not much effective) and tweak the plugin options as suggested in the plugin docs.

**Comment by Nikhil-Ladha** [comment]
You might have to add more links/directives in the options for our site like the `font-src` directive and the `meshery.layer.io`  under script.

**Comment by RishabhKodes** [comment]
@Nikhil-Ladha I've defined the directive rules [here](https://github.com/layer5io/layer5/pull/3777/files#diff-b5e305780d9d473da97c61beab8bc36e5e8871b360942e4686c9b20d8c5d4cfaR34-R37), PTAL. These are the most basic and lenient rules, let me know if you feel some changes are required.
