### ISSUE TITLE
[UI] The SCA logo should be replaced with light-version when site in dark-mode on Programs page

### ISSUE THREAD

**Issue by Anita-ihuman** [layer5io/layer5#3789]
### Description
The SCA logo is not so visible in dark mode

### Expected Behavior
The color of the SCA logo should be visible in darkmode on the Programs page. And able to toggle between light mode and dark mode.
Find the various SVG files to the logo here
- https://drive.google.com/drive/folders/12jwnp_ft1gNb-wM_HvZjSmV_DGfopf1T

### Screenshots
<img width="1282" alt="Screenshot 2023-02-20 at 9 49 32 AM" src="https://user-images.githubusercontent.com/62384659/220057202-d9588213-366f-4206-83ab-6b812cda7f99.png">

### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by oneknucklehead** [comment]
Hey @Anita-ihuman can you assign me this issue?

**Comment by Rishikavishnoi** [comment]
@Anita-ihuman Can I work on it ..?

**Comment by AbhiiVops** [comment]
Hello @Anita-ihuman ,

I hope this message finds you well. I am writing to express my interest in contributing to the project by **working on issue #3789 The SCA logo should be replaced with light-version when site in dark-mode on Programs page.** 

If it's alright with you, could you please assign this issue to me? I would be happy to collaborate with other team members to ensure that the logo is created in a timely manner and meets the project's requirements.

Thank you for your consideration, and I look forward to hearing back from you soon.

Best regards,
**Abhishek Bhattacharjee**

**Comment by Darrendsouza1111** [comment]
Can i work on this issue

**Comment by Rishikavishnoi** [comment]
@Darrendsouza1111 or @AbhiiVops you can work on this issue...
I'm quite busy so I  unassigned myself...

**Comment by Darrendsouza1111** [comment]
> @Darrendsouza1111 or @AbhiiVops you can work on this issue...
> 
> I'm quite busy so I  unassigned myself... 

Ok thank you so much

**Comment by Darrendsouza1111** [comment]
@Anita-ihuman can u assign this issue to me

**Comment by pratik-osta** [comment]
Can you please assign me this issue

**Comment by randychilau** [comment]
Hi All,

There may be some confusion regarding the status of this issue as there are: 

- requests from contributors to be assigned this issue
- no current [assignees](https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users)
- an existing PR under review that mentions this issue which may signal that this issue is currently being addressed (however not certain).

This [issue #3789](https://github.com/layer5io/layer5/issues/3789#issue-1591411965) wants to resolve the SCA logo on this page:
https://layer5.io/programs/sca-contributhon

PR 4046 seen above is working to resolve the SCA logo on this page:
https://layer5.io/community/handbook/mentorship-programs

While the pages are different, they both use the same image file which is the focus of issue 3789 and PR 4046:
`src/collections/programs/sca-contributhon/sca.svg`

Assigning this issue to someone else now instead of the author of PR 4046 could introduce competing changes on the image file. 

In an effort to minimize confusion, I suggest that this issue be considered assigned to the author of PR 4046 until the PR review process for 4046 is completed.

Cheers,
Randy

**Comment by HetviSoni** [comment]
As I am working on the similar issue https://github.com/layer5io/layer5/issues/4228 , I would like to work on this issue.

**Comment by DarrenDsouza7273** [comment]
@HetviSoni can u please update?

**Comment by aabidsofi19** [comment]
@Anita-ihuman 

I would like to work on this issue , with experience in front-end development, I am confident in resolving these issues effectively. I would appreciate being assigned this task to contribute to the improvement of the Meshery experience for new users.

Thank you for considering my request.

Best regards,
Aabid Sofi

**Comment by HetviSoni** [comment]
> @HetviSoni can u please update?

Sorry for the delay. Actually I was facing some errors in setting up the project.
I have solved the issue. Can you please assign me so that I can include it in my pr (https://github.com/layer5io/layer5/pull/4293)

**Comment by DarrenDsouza7273** [comment]
@vishalvivekm could you please assign this issue to @HetviSoni

**Comment by DarrenDsouza7273** [comment]
@HetviSoni you can work on it now
