### ISSUE TITLE
[MeshMap] Mobile: Touch gesture not detected as scroll event

### ISSUE THREAD

**Issue by Shivam-AfA** [layer5io/layer5#3808]
### Description
- In the mobile view of the meshmap page, the features sections do not detect mobile touch as scroll events. Consequently, the SVG animations are not invoked, but are skipped instead. 

https://user-images.githubusercontent.com/88040318/220980456-0f8b7e8c-8e3f-470b-bb8e-81e4baa4e239.mp4

### Environment:
- Host OS: IOS - iPhone

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by divz-codess** [comment]
@Shivam-AfA we can add scroll bar in each section and a collapse button "-" to collapse the particular section. This will help in knowing when we are scrolling the inner section and when the outer one is being scrolled. 
@leecalcote your thoughts on it?
If this looks good I can start working on it and you can assign me.

**Comment by leecalcote** [comment]
@divz-codess, you have some well-placed suggestions here. There is a bit of historical context to bring you up to speed on, prior to considering a full accordion effect.

Until you're able to catch up with @Shivam-AfA, an alternative bit of research in this area would be very helpful. We need to evaluate use of other packages that have robust support for controlling scrolling on a page (e.g. scrollspy-like packages for React). The event listeners and handlers for scrolling on the MeshMap page are custom-implemented and they are  having a bit of trouble. 

**Challenge #1:** Scroll events are not listened to/captured when the visitor's mouse is on either side of the page (in the page gutters), which which isn't good because then the site visitor simply misses all of the animations as they scrolled right past them.

**Challenge #2:** When the site visitor's mouse _is_ hovering over the sections, the animations are sometimes stuck as the bottom of the page and not visible, so the visitor is scrolling, the page isn't moving, and they are not seeing the animation. Also, when the visitor reaches the bottom and scrolls back up the page, the animations should play in reverse, but there is misbehavior here as well. 

**Action:** Let's investigate use of an an existing React/npm/open source package with better behavior and logic, ensuring that all of the behaviors described above are addressed.

**Comment by divz-codess** [comment]
@leecalcote thanks for the insights I'll look into it :)
