### ISSUE TITLE
[MeshMap] Visualizer page design required: Log Streaming

### ISSUE THREAD

**Issue by Shivam-AfA** [layer5io/layer5#3882]
### Desired Situation

A UI design is required for a section for new MeshMap page that'll highlight this feature of the Visualizer: 

![image](https://user-images.githubusercontent.com/88040318/222732854-7cf9f4f4-a618-4318-8464-dab1d8d5a4d7.png)

More info: https://layer5.io/cloud-native-management/meshmap/

MeshMap figma designs: https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=2074%3A853

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by harshal0815** [comment]
@Shivam-AfA Can I work on this? I have prior Product management and UI/UX experience. If possible could you kindly elaborate on the issue about what I can do and review the contribution afterward?

**Comment by Shivam-AfA** [comment]
Sure @harshal0815. Thanks for jumping in. You can learn more about this at https://play.meshery.io/. You can also sign up for meshmap here https://layer5.io/cloud-native-management/meshmap, and try out meshery docker extension to work with the different features of Meshmap visualizer.

**Comment by harshal0815** [comment]
@Shivam-AfA Actually I'm completely new to the project. I have completed going through the guidelines and handbook, apart from setting up the local dev environment. I'm still a bit unsure of the requirements and expected deliverables. If possible can we have a session so that I can also possibly finish working on the other five UI/UX issues later on, for the Meshmap visualizer? I have experience in UI/UX and proficiency in Figma. Currently, I'm unable to visualize a specific design for the feature. Kindly let me know if there is anything I can do from my end. Thanks.

**Comment by Shivam-AfA** [comment]
I'm tagging @leecalcote to guide you further.
