### ISSUE TITLE
Follow up on  scroll trigger #3895 

### ISSUE THREAD

**Issue by Udit-takkar** [layer5io/layer5#3921]
### Current Behavior
https://github.com/layer5io/layer5/pull/3895#issuecomment-1455163817
https://github.com/layer5io/layer5/pull/3895#issuecomment-1455167270

### Desired Situation

Need to fix scrolling issues in mobile and tall height screens

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Shivam-AfA** [comment]
@Udit-takkar Any progress here?

**Comment by Shivam-AfA** [comment]
@Udit-takkar Nice. You have a really important item on your hands here. We're relying on you, since you have portrayed an amazing skillset by working on a new library and getthig the scroll thing done. 

By the way, the main issue on mobile includes the section getting stuck sometimes and the user tends to skip the animations on scroll. How do you plan to make the scroll speeds differ on mobile devices? Is there any functionality provided in the GSAP library?

**Comment by Udit-takkar** [comment]
@Shivam-AfA actually I did try few things like using scroll snap to improve scroll experience but it didn't work. Sorry for the delay

**Comment by Shivam-AfA** [comment]
So do you have any other ideas in your mind @Udit-takkar
