### ISSUE TITLE
[Careers] Post New LFX Summer 2023 Internships

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#4208]
### Current Behavior
The [LFX programs page](https://layer5.io/programs/lfx) needs the Summer term listed.

### Desired Situation
Add details of:

- https://github.com/cncf/mentoring/blob/main/programs/lfx-mentorship/2023/02-Jun-Aug/project_ideas.md#service-mesh-performance
- https://github.com/cncf/mentoring/blob/main/programs/lfx-mentorship/2023/02-Jun-Aug/project_ideas.md#meshery

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by aku1310** [comment]
Hi @leecalcote! I would like to work on this issue.

**Comment by leecalcote** [comment]
Thank you.

**Comment by aku1310** [comment]
I wanted to seek advice regarding one thing.

I am applying the numbered lists in expected outcome section so that it does not get confused with the rest of the bullet points (recommended skills, mentors, etc.). Would this be fine to apply? 😅 

Image for reference:
![image](https://github.com/layer5io/layer5/assets/72210364/b1386258-7793-46fe-b7a0-264de786b62d)

I also noticed that in one of the Spring project, this is the case as well. The deliverables are getting mixed up with the rest of the bullet points

Image for reference:
![image](https://github.com/layer5io/layer5/assets/72210364/bc7ac612-a2af-4aff-96e5-0d26e4480330)

If the numbered listing works (or any other type which might seem better), then I can fix it there as well.

**Comment by leecalcote** [comment]
@vishalvivekm ^^

**Comment by vishalvivekm** [comment]
@aku1310 
Sounds great, Yeah we'd want to have deliverables/outcomes separated from sections such as required skills and mentors.
Which's to say, you get the green-light, Yes please go ahead with it.

**Comment by aku1310** [comment]
Okay, thank you!
