### ISSUE TITLE
[Community] Member Profile: Savio Dias

### ISSUE THREAD

**Issue by vishalvivekm** [layer5io/layer5#4275]
**Current Behavior**

@savio629 has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @Savio629  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @Savio629 
- Twitter: [Savio_dias629](https://twitter.com/Savio_dias629)
- LinkedIn: [savio-dias-984b45198](https://www.linkedin.com/in/savio-dias-984b45198/)
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by vishalvivekm** [comment]
Profile picture and a bio, please @Savio629 :sunglasses:

**Comment by vishalvivekm** [comment]
Much Thanks @darrendsouza7273

**Comment by Savio629** [comment]
Profile pic : https://drive.google.com/file/d/1P7pX5z2B2-LLh22yq6RZyHbCQyz7O-4K/view?usp=sharing
Bio : Hey there! I'm Savio Dias, a tech enthusiast with a great curiosity for exploring the endless possibilities of technology. As a student at FCRIT, Vashi, I discovered the world of open-source during my sophomore year and I've been hooked ever since. With a keen interest in UI/UX and a good foundation in the MERN stack, I'm always eager to expand my knowledge and dive into the dynamic realms of cloud-native technologies and APIs. My commitment to open-source stems from my belief in the power of collaborative learning and community-driven growth. I'm ready to embark on a coding adventure together! Let's connect and let our journey begin with a resounding "Link start" into the realm of technology!

**Comment by DarrenDsouza7273** [comment]
workin on it @Savio629
