### ISSUE TITLE
[Slack] Create subscription checkboxes for new Slack user signups

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#447]
**Current Behavior**
The http://slack.layer5.io sign up form does not provide users the option to subscribe to the community mailing list (https://layer5.io/subscribe).

**Desired Behavior**
Offer a checkbox to allow users to subscribe to the community mailing list like the two subscription checkboxes offered on the Linkerd Slack signup:

<img width="443" alt="Screen Shot 2020-06-13 at 4 05 36 PM" src="https://user-images.githubusercontent.com/7570704/84579028-22440380-ad90-11ea-827d-4b154c1cb8fd.png">

**Comment by chandrashritii** [comment]
@leecalcote Could you shed some light on where I could find the source file or how I can edit the slack sign up form?
I made and built the changes locally. I'm attaching a screenshot to show the effect.

![Screenshot_2020-06-19 Join Layer5 on Slack ](https://user-images.githubusercontent.com/34476976/85084740-4f127380-b1f3-11ea-9095-6e7911675877.png)

**Comment by leecalcote** [comment]
Oh, perfect. Yes, this change will be done a little differently than almost all others across our projects. This is an instance of [slackin](https://github.com/rauchg/slackin) and is running in a free dyno on Heroku. It's been too long since this deployment has been touched. Let dig up and get you these details.

**Comment by chandrashritii** [comment]
@leecalcote 
Any idea where I could find details (links, config files etc.) about the dyno used on Heroku?

I looked up slackin and found a [slackin-extended](https://github.com/emedvedev/slackin-extended) version of the original slackin repo, which seems to be a better idea.
Following the Readme instructions should help us set up a new sign up form with the added subscription checkbox and any other updates you would like.
Also, going by the instructions in  [extras](https://github.com/emedvedev/slackin-extended#extras), I would need an admin to generate the legacy token. Can that be done?

**Comment by leecalcote** [comment]
@chandrashritii great suggestion on use of slackin-extended. Let's do it. Yes, I have a legacy Slack token waiting for you. 👍

**Comment by chandrashritii** [comment]
@leecalcote Slack doesn't support generating new API legacy tokens anymore. It instead only allows the creation of Slack apps (refer ~ [Legacy-tokens/Slack](https://api.slack.com/legacy/custom-integrations/legacy-tokens)). A new Legacy token is a requirement for `slackin`, which is why deploying through Heroku isn't possible. 
This is an official [issue](https://github.com/rauchg/slackin/issues/416) listed in the `slackin` as well as `slackin-extended` repo. 
As an alternative to using `slackin`, Slack now allows work spaces to generate invite URLs without an expiry date, which notifies the admin every time a user signs up and can be shared to up to 2000 people.

I realize this doesn't solve the original issue of adding a checkbox for the community mailing list but the only way to do that now (that I can think of) is to build a node.js app and deploy independently through Heroku or another platform. Please let me know if you want to try that :)
Also, I tried creating a new workspace "Trials" and generated a sign up form using Slack. I'm attaching a screenshot of the same to give you an idea of the end result

![Screenshot_2020-06-22 Create Account](https://user-images.githubusercontent.com/34476976/85236992-a0fc0900-b440-11ea-9630-6ad750f6cf00.png)

**Comment by kushthedude** [comment]
A better option, let's fork the slackin repository and make changes according to our need. I went through the code and it's pretty much a traditional spa with gulp.

**Comment by leecalcote** [comment]
Given today's discussion, let's set aside this request for the time being. Thank you for digging into this, @chandrashritii.
