### ISSUE TITLE
Modification of READEME.md file

### ISSUE THREAD

**Issue by Debaditya-Som** [layer5io/layer5#4705]
A suggested feature request : Addition of Contributors list in the README.md file

**Comment by sm-creative-crazy4code** [comment]
hi @Debaditya-Som  can I please work on this issue

**Comment by Ghat0tkach** [comment]
@Debaditya-Som  , We have around 450 contributors and that would definitely make list soooo long.
Rather than being in readme how bout a member profile on our Layer5 website to showcase your achievement?
We actively reward contributors with invites to layer5 and meshery organization and a member profile!!
Please check out https://layer5.io/community/handbook/recognition for more details.

**Comment by sm-creative-crazy4code** [comment]
@Ghat0tkach  shall I create a new  page in layer5 website for contributors .  Can I contribute to the platform in that way.   I guess I can pull the contributors list easily from the git hub API and render them on the webpage . That will be better I guess README is required to be updated every time a new contributor is added. Please do let me know if I could contribute in that way.

**Comment by malaviya-parth** [comment]
@Debaditya-Som can I contribute to this issue?

**Comment by Ghat0tkach** [comment]
@sm-creative-crazy4code  , I think you missed my point please read it again😅. We at Layer5 reward you with Member profile on our website! It's way better than to be on a readme doc.
