### ISSUE TITLE
Duplicate meta descriptions

### ISSUE THREAD

**Issue by vishalvivekm** [layer5io/layer5#4805]
### Current Behavior

Currently, these 4 pages have duplicate meta descriptions (og:description)
- https://layer5.io/blog/docker/extending-the-docker-compose-experience-to-service-mesh
- https://layer5.io/blog/docker/extending-docker-with-meshery-spire-and-istio
- https://layer5.io/resources/case-study/hpes-adoption-of-meshery-and-meshmap
- https://layer5.io/company/news/layer5-and-hashicorp-launch-service-mesh-partnership

Note:  Ctrl+U – Open the pages' source code and search for og:description to see the meta description

### Desired Situation

Each of these pages should have different content for og:description property in meta tag.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Mohith234** [comment]
I would like to work on this

**Comment by vishalvivekm** [comment]
Thanks @abhijeetgauravm. // @Mohith234 🚀

**Comment by vishalvivekm** [comment]
@Mohith234 would you sound off with your updates on Monday' websites call?
Here's the meeting minutes: [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima),

**Comment by Mohith234** [comment]
All of the `.mdx` pages have this same description not only these 4 pages. 

This is because the description that is present in the `frontmatter` is not retrieved at the SEO component. I tried to log the variables but found it as an empty string. Whereas the title is being retrieved from the query and shown up in the `og:title` field.

Output when logged  `description`, `defaultDescription`, `title`, `defaultTitle`

![image](https://github.com/layer5io/layer5/assets/88539464/827e8549-1f62-4768-a6e7-dac50576475b)

**P.S** I may not attend today's meeting so updating the problem here

**Comment by randychilau** [comment]
Hi All,

As @Mohith234 mentioned, `frontmatter` information in the`.mdx` pages is not being passed to the SEO component as the `description` prop in their respective template pages.

One approach to this issue is to update the respective template page by doing the following:

for example: `src/templates/blog-single.js`
- adding the desired field to the graphql query:
![image](https://github.com/layer5io/layer5/assets/90356410/10c334a8-bc0c-47b6-9a8f-cd704c8601cf)
- adding the field to the SEO component:
![image](https://github.com/layer5io/layer5/assets/90356410/dd84956a-a49d-4a57-96b0-2fe592faca59)

and checking the source code:

for example: `src/collections/blog/2023/2023-06-15-internship-experience-blog-sudhanshu-dasgupta/index.mdx`

![image](https://github.com/layer5io/layer5/assets/90356410/566b09a7-2e6b-4ced-bfe9-7f89caa16dfe)

>note: for folders of mdx pages, the frontmatter field to use for the `description` prop may be different

Hope this information helps.

Cheers,
Randy

**Comment by Mohith234** [comment]
@randychilau Yep, that works fine. Thanks for the fix 🙌
