### ISSUE TITLE
[Community] Member Profile: Suruchi Kumari

### ISSUE THREAD

**Issue by saurabh100ni** [layer5io/layer5#5099]
**Current Behavior**

@coder12git  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @coder12git as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @coder12git 
- Twitter: [Suruchi18591098
](https://twitter.com/Suruchi18591098)
- LinkedIn: [in/suruchi-kumari-5b3445230](https://www.linkedin.com/in/suruchi-kumari-5b3445230/)
- Layer5 Cloud: 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by saurabh100ni** [comment]
@coder12git please share following:

- Layer5 Cloud: 
- Link to profile picture:
- bio:

**Comment by Harsha-10** [comment]
I would like to work on it

**Comment by abhijeetgauravm** [comment]
There u go @Harsha-10

**Comment by coder12git** [comment]
> @coder12git please share following:
> 
> * Layer5 Cloud:
> * Link to profile picture: 
> * bio:

Sure @saurabh100ni 
* Layer5 Cloud*:  [https://meshery.layer5.io/user/1884fea6-0450-4404-9560-e0383f0e8cd7](https://meshery.layer5.io/user/1884fea6-0450-4404-9560-e0383f0e8cd7)
* Link to profile picture*:  [pic](https://github.com/layer5io/layer5/assets/108334168/3bbd1406-8c54-425d-90ae-f720399ccd90)
*bio*: ` Hello, I'm Suruchi Kumari, a full-stack Web Developer based in India. I enjoy  contributing to open source projects and taking part in Hackathons. I believe the best way to learn new technology is by doing, which is why I contribute to open source projects. I'm also a people person, so feel free to reach out to me on my social media profiles.`

**Comment by coder12git** [comment]
@Harsha-10 great, I am looking forward to this PR :)

**Comment by Harsha-10** [comment]
@coder12git can you please send your pic with more clarity or may be a drive link? the pic is blurred and isn't looking good...

**Comment by coder12git** [comment]
> @coder12git can you please send your pic with more clarity or may be a drive link? the pic is blurred and isn't looking good...

https://drive.google.com/file/d/1mf2GLtWbzjH5uIQy_bcvYd1kNBtlnZfy/view?usp=drivesdk
