### ISSUE TITLE
Add Siege as a tool to landscape

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#52]
Hi @JoeDog, @sohamm17, @jmarantz, will you consider adding a listing for https://github.com/JoeDog/siege to the [service mesh landscape](https://layer5.io/landscape) under the [Tools](https://github.com/layer5io/layer5/blob/master/_includes/service-mesh-tools.html) section? Given its use within the envoy-perf project, we'd love to have an accurate listing of the tool described here.

**Comment by leecalcote** [comment]
@jmarantz I hadn't realized I'd previously tagged you here. We came full-circle. :)

**Comment by JoeDog** [comment]
What do I have to do?

**Comment by yogi4** [comment]
Jeff (@JoeDog ), 
In your case since Siege has to be added to tools section 

you can edit 
layer5->_includes-> service-mesh-tools.html file. 

layer5/_includes/service-mesh-tools.html and add a row for siege tool 

This site is powered my Jekyll .  In order to edit/ add service Mesh Landscape details we have to edit yml files  data section. 

under Layer5 , there is a section called _data 
layer5->-data->categories-> *.yml 

you can edit the relevant yml files to add/edit details to the service mesh landscape. 

In your case since Siege has to be added to tools section

**Comment by leecalcote** [comment]
@JoeDog we're scrubbing issues today, so I'm giving this one a bump. We'll be presenting this landscape at the upcoming KubeCon EU.

**Comment by jijillery** [comment]
Hi  @JoeDog, @sohamm17, @jmarantz, I’m working to ensure all relevant projects are represented in the [service mesh landscape](https://layer5.io/landscape). We would love to have Siege included. Will you consider updating the landscape with a quick pull request? 

We do our best to ensure that projects and their capabilities are accurately represented, and so, we ask for project representatives to submit these updates directly. 

Here are [contribution instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md) for making your edits.

Thank you!
@jijillery

**Comment by nveenjain** [comment]
Closing in favor of #195, please re-open if required!
