### ISSUE TITLE
[Community] Layer5 Community Meetings table not mobile responsive

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#785]
This table (https://layer5.io/community#meetings) is not configured to be responsive in a mobile view.

It needs to be responsive. There are existing styles in the site that can be used to make it responsive.

![Screenshot_20200918-093727__01](https://user-images.githubusercontent.com/29438875/93555147-cbebef80-f992-11ea-9473-b920f726ce23.jpg)
One issue with the table in mobile view.

_Originally posted by @Nikhil-Ladha in https://github.com/layer5io/layer5/pull/764#issuecomment-694638322_

**Comment by chandrashritii** [comment]
@clementkng would you like to take this up?

**Comment by clementkng** [comment]
@chandrashritii Yes, thank you! Interested in helping out any way I can 🙂

**Comment by clementkng** [comment]
Hi @chandrashritii to make this table responsive, do you think it's enough to make all the options accessible by horizontal scroll ie by either changing the overflow-x property to `auto` or utilizing the "responsive-table" class (which introduces its own styling that will need to be overridden) or should I try to make a custom media rule to shrink the table? Asking you because you introduced the table.

**Comment by Nikhil-Ladha** [comment]
I think it would be better to introduce a horizontal scroll, rather than shrinking the table that way the data will be more visible.
