### ISSUE TITLE
Add Grey Matter to the Functional Service Mesh list

### ISSUE THREAD

**Issue by brianlitalien** [layer5io/layer5#83]
Please add Grey Matter to the functional service mesh list. 

Decipher Technology Studios' Grey Matter intelligent service mesh is a cloud-native, cloud agnostic intelligent service mesh that saw its formal 1.0 release on 14 Feb. 

A pathway for enterprise transformation and cost control, Grey Matter is comprised of three layers, Fabric, Data, and Sense, working in unison to manage enterprise microservice fleets. The capture and analysis of over 100 telemetry types powers SLA management and control. Grey Matter is also designed to optimize enterprise network availability and performance through the innovative use of AI neural networks, enabling AIOPs.   

Repositories and other documentation can be found here: https://demo.deciphernow.com/

**Comment by yogi4** [comment]
@brianlitalien Below are the instructions to add Grey Matter to the Functional Service Mesh List 

This site is powered by Jekyll .  In order to edit/ add service Mesh Landscape details we have to edit yml files  data section. 

Under Layer5 , there is a section called _data/categories 
You will notice a file named meshes.yml 
layer5->-data->categories-> meshes.yml 
(https://github.com/layer5io/layer5/blob/master/_data/categories/meshes.yml) 
Please edit this file to add Grey Matter to the Functional Service Mesh List , we would recommend adding this in alphabetical order . 
You would need to fill in this list below and add it to meshes.yml 

  name: Grey Matter
  desc: 
  link: https://demo.deciphernow.com/
  autoinject:   #Yes or NO 
  h2: 
  grpc: 
  tcp-web: 
  multi-cluster: 
  multi-tenant: 
  prometheus: 
  tracing: 
  encryption: 

Please feel free to reach out to me if you need any help regarding this.

**Comment by brianlitalien** [comment]
https://github.com/layer5io/layer5/pulls

**Comment by leecalcote** [comment]
@brianlitalien thanks for contributing here!

**Comment by leecalcote** [comment]
@brianlitalien @joshua-rutherford one item that wasn't pointed out in the instructions is to add an entry in the non-functional section as well - https://github.com/layer5io/layer5/blob/master/_data/categories/non-functional.yml. Could you include a stanza for Grey Matter?

**Comment by leecalcote** [comment]
Fixed by #84.
